# Generated by Django 6.0.3 on 2026-03-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30, unique=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('first_half', '1st Half (1–15)'), ('second_half', '2nd Half (16–End)'), ('custom', 'Custom Range')], max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('luggage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
