# Generated by Django 6.0.3 on 2026-03-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Flower Agency', max_length=200)),
                ('owner_name', models.CharField(default='Agent Name', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('default_flower', models.CharField(default='Rose', max_length=100)),
                ('default_rate', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
                ('default_comm_type', models.CharField(default='percent', max_length=10)),
                ('default_comm_value', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('billing_pref', models.CharField(default='monthly', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Configuration',
            },
        ),
    ]
