# Generated by Django 6.0.3 on 2026-03-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('first_half', '1st Half (1–15)'), ('second_half', '2nd Half (16–End)')], default='monthly', max_length=15)),
                ('comm_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount (₹)')], default='percent', max_length=10)),
                ('comm_value', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
    ]
