# Generated by Django 6.0.3 on 2026-03-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('flower_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('luggage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='members.member')),
            ],
            options={
                'ordering': ['-entry_date', 'member__store_name'],
                'unique_together': {('member', 'entry_date', 'flower_name')},
            },
        ),
    ]
